<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>
    <div class="container-fluid">
 <?php  
  echo $this->tag->linkTo('login/index','  <button type="button" onclick="" class="btn btn-danger">LOGOUT</button> ');
   ?>
   
        <?php echo $this->getContent(); ?>
    </div>
</body>

</html>